name : Игорь Бояндин
brand : Игорь Бояндин
dates : 08.11.1954 - 03.01.1990
description : Страница памяти Игоря Бояндина
keyword:  
url : http://igor.boyandin.me
email : igor@boyandin.me
author: Ilya Boyandin
